---

# A tic-tac-toe text-console game implemented in Ansible.
# Idea and implementation: Maxim B. Belooussov

- name: Starting a new game
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    available_fields: []
    A0: " "
    A1: " "
    A2: " "
    B0: " "
    B1: " "
    B2: " "
    C0: " "
    C1: " "
    C2: " "
    board_array:
      - name: A0
        value: "{{ A0 }}"
      - name: A1
        value: "{{ A1 }}"
      - name: A2
        value: "{{ A2 }}"
      - name: B0
        value: "{{ B0 }}"
      - name: B1
        value: "{{ B1 }}"
      - name: B2
        value: "{{ B2 }}"
      - name: C0
        value: "{{ C0 }}"
      - name: C1
        value: "{{ C1 }}"
      - name: C2
        value: "{{ C2 }}"

  # there can be only up to 9 moves, so just code them all
  tasks:
    - name: User makes move 1
      import_tasks: usermove.yml

    - name: We make move 2
      import_tasks: ourmove.yml

    - name: User makes move 3
      import_tasks: usermove.yml

    - name: We make move 4
      import_tasks: ourmove.yml

    - name: User makes move 5
      import_tasks: usermove.yml

    - name: We make move 6
      import_tasks: ourmove.yml

    - name: User makes move 7
      import_tasks: usermove.yml

    - name: We make move 8
      import_tasks: ourmove.yml

    - name: User makes move 9
      import_tasks: usermove.yml

    - name: We run out of moves
      debug:
        msg: "No more moves left!"
